### ISSUE TITLE
MAC compliant?

### ISSUE THREAD

**Issue by danelige** [sevkeifert/text-utils#1]
how can this be made mac-useable? 
can srm command be used (https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/srm.1.html) or just install shred?

**Comment by sevkeifert** [comment]
This is for the svi script?  Yes, I'd recommend installing **shred** or changing the line in the script to something else.   

The reason for this: removing an unencrypted file just unlinks it, but the data is still on the disk.  Shred actually overwrites the file.  So, without the shred line, the encryption method is not very secure.

This line can be replaced with any utility that securely removes a file.
